- name: install zShell
  pkgng:
    name: "{{ zshell_packages }}"
    state: present

- name: config zsh for user
  block:

    - name: set zshell for user
      command: 'chsh -s /usr/local/bin/zsh {{ item }}'
      loop:
        - "{{ bootstrap_zsh_user }}"
      #when: ( bootstrap_zsh_user is defined )

    - name: set .zshrc file
      template:
        src: zshrc.j2
        dest: "/home/{{ item }}/.zshrc"
        owner: {{ item }}
        group: wheel
        mode: 0644
      loop:
        - "{{ bootstrap_zsh_user }}"

  when: ( bootstrap_zsh_user is defined )
